name: flutter_about_cat
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  font_awesome_flutter: ^9.1.0
  photo_view: ^0.12.0
  url_launcher: ^6.0.11
  flutter_staggered_grid_view: ^0.4.0
  transparent_image: ^2.0.0
  google_fonts: ^2.1.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  
  android: "launcher_icon"
  ios: true
  image_path: "img/catlogo.png"  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0



flutter:

  
  uses-material-design: true

  assets:
    - img/

  